insert into ref_metodo_ir values(10300,'Instalação de armário metálico');
insert into ref_metodo_ir values(10300,'Instalação de armário óptico');
insert into ref_metodo_ir values(10300,'Retirada de armário metálico');
insert into ref_metodo_ir values(10300,'Retirada de armário óptico');
insert into ref_metodo_ir values(19500,'Instalar Aterramento');
insert into ref_metodo_ir values(2900,'Construção de pedestal de armário metálico');
insert into ref_metodo_ir values(2900,'Construção de pedestal de armário óptico');
insert into ref_metodo_ir values(17100,'Confecção de bloqueio');
insert into ref_metodo_ir values(7000,'Adicional para instalação simultânea de cabo aéreo');
insert into ref_metodo_ir values(7000,'Adicional para instalação simultânea de cabo interno');
insert into ref_metodo_ir values(7000,'Adicional para instalação simultânea de cada cabo em um mesmo duto');
insert into ref_metodo_ir values(7000,'Adicional para retirada simultânea de cabo aéreo');
insert into ref_metodo_ir values(7000,'Adicional para retirada simultânea de cabo interno');
insert into ref_metodo_ir values(7000,'Adicional para retirada simultânea de cabo subterrâneo');
insert into ref_metodo_ir values(7000,'Instalação de cabo adicional em cordoalha com cabos existentes');
insert into ref_metodo_ir values(7000,'Instalação De Cabo Espinado');
insert into ref_metodo_ir values(7000,'Instalação De Cabo Inclusive Óptico Em Duto Ocupado');
insert into ref_metodo_ir values(7000,'Instalação de Cabo Interno');
insert into ref_metodo_ir values(7000,'Instalação de cabo interno em duto ocupado');
insert into ref_metodo_ir values(7000,'Instalação De Cabo Subterrâneo Acima De 300 Até 900 Pares');
insert into ref_metodo_ir values(7000,'Instalação De Cabo Subterrâneo Acima De 900 Pares');
insert into ref_metodo_ir values(7000,'Instalação De Cabo Subterrâneo Até 300 Pares, Inclusive Óptico E Coaxial');
insert into ref_metodo_ir values(7000,'Retirada De Cabo Espinado');
insert into ref_metodo_ir values(7000,'Retirada De Cabo Espinado com permanência de outro');
insert into ref_metodo_ir values(7000,'Retirada de Cabo Interno');
insert into ref_metodo_ir values(7000,'Retirada De Cabo Subterrâneo Acima 300 Pares');
insert into ref_metodo_ir values(7000,'Retirada De Cabo Subterrâneo Até 300 Pares inclusive óptico');
insert into ref_metodo_ir values(7000,'Retirada De Cabo Subterrâneo Com A Permanência De Outro');
insert into ref_metodo_ir values(7200,'Adicional para instalação simultânea de cabo aéreo');
insert into ref_metodo_ir values(7200,'Adicional para instalação simultânea de cabo interno');
insert into ref_metodo_ir values(7200,'Adicional para retirada simultânea de cabo aéreo');
insert into ref_metodo_ir values(7200,'Adicional para retirada simultânea de cabo interno');
insert into ref_metodo_ir values(7200,'Adicional para retirada simultânea de cabo subterrâneo');
insert into ref_metodo_ir values(7200,'Instalação de cabo adicional em cordoalha com cabos existentes');
insert into ref_metodo_ir values(7200,'Instalação De Cabo Auto-Sustentável');
insert into ref_metodo_ir values(7200,'Instalação de Cabo Enterrado');
insert into ref_metodo_ir values(7200,'Instalação de Cabo Enterrado Manual');
insert into ref_metodo_ir values(7200,'Instalação De Cabo Espinado');
insert into ref_metodo_ir values(7200,'Instalação De Cabo Inclusive Óptico Em Duto Ocupado');
insert into ref_metodo_ir values(7200,'Instalação de Cabo Interno');
insert into ref_metodo_ir values(7200,'Instalação de cabo interno em duto ocupado');
insert into ref_metodo_ir values(7200,'Instalação De Cabo Subterrâneo Até 300 Pares, Inclusive Óptico E Coaxial');
insert into ref_metodo_ir values(7200,'Retirada de cabo auto-sustentável');
insert into ref_metodo_ir values(7200,'Retirada De Cabo Espinado');
insert into ref_metodo_ir values(7200,'Retirada De Cabo Espinado com permanência de outro');
insert into ref_metodo_ir values(7200,'Retirada de Cabo Interno');
insert into ref_metodo_ir values(7200,'Retirada De Cabo Subterrâneo Até 300 Pares inclusive óptico');
insert into ref_metodo_ir values(7200,'Retirada De Cabo Subterrâneo Com A Permanência De Outro');
insert into ref_metodo_ir values(2700,'Construção De Caixa Subterrânea em Alvenaria');
insert into ref_metodo_ir values(2700,'Construção De Caixa Subterrânea em Concreto Armado');
insert into ref_metodo_ir values(2600,'Instalação De Cordoalha');
insert into ref_metodo_ir values(2600,'Retirada de cordoalha');
insert into ref_metodo_ir values(19600,'Instalação de sub-bastidor (módulo) com cordão monofibra. conectores e adaptadores');
insert into ref_metodo_ir values(2400,'Construção de linha até 3 dutos');
insert into ref_metodo_ir values(2400,'Construção de linha de 10 a 16 dutos');
insert into ref_metodo_ir values(2400,'Construção de linha de 17 a 20 dutos');
insert into ref_metodo_ir values(2400,'Construção de linha de 21 a 28 dutos');
insert into ref_metodo_ir values(2400,'Construção de linha de 29 a 36 dutos');
insert into ref_metodo_ir values(2400,'Construção de linha de 4 a 6 dutos');
insert into ref_metodo_ir values(2400,'Construção de linha de 7 a 9 dutos');
insert into ref_metodo_ir values(2400,'Instalação de dutos acima de 50 mm MND');
insert into ref_metodo_ir values(2400,'Instalação de dutos até de 50 mm MND');
insert into ref_metodo_ir values(2400,'Instalação de dutos em nicho ou faixa de servidão da ponte');
insert into ref_metodo_ir values(2400,'Instalação de dutos em travessia suspensa');
insert into ref_metodo_ir values(10800,'Abertura/fechamento emenda cabo aéreo');
insert into ref_metodo_ir values(10800,'Emenda de cabo aéreo funcionando');
insert into ref_metodo_ir values(10800,'Emenda de cabo aéreo morto');
insert into ref_metodo_ir values(11800,'Abertura/fechamento emenda cabo óptico (aéreo/subterrâneo)');
insert into ref_metodo_ir values(11800,'Emenda de cabo óptico funcionando (aéreo) ');
insert into ref_metodo_ir values(11800,'Emenda de cabo óptico funcionando (subterrâneo)');
insert into ref_metodo_ir values(11800,'Emenda de cabo óptico morto (aéreo) ');
insert into ref_metodo_ir values(11800,'Emenda de cabo óptico morto (subterrâneo)');
insert into ref_metodo_ir values(11900,'Instalação de sub-bastidor (módulo) com cordão monofibra. conectores e adaptadores');
insert into ref_metodo_ir values(3000,'Instalação De Poste');
insert into ref_metodo_ir values(3000,'Retirada de poste');
insert into ref_metodo_ir values(10900,'Instalação De Caixa Predial');
insert into ref_metodo_ir values(10900,'Instalação De Caixa Terminal');
insert into ref_metodo_ir values(10900,'Retirada de caixa terminal');
insert into ref_metodo_ir values(19300,'Instalação de transdutor');
insert into ref_metodo_ir values(19300,'Retirada de transdutor');
commit;


insert into REF_FTYPE_CRE values(2600, 'CORDOALHA RD EXT ACO BENZINAL 4,55MM 3F');
insert into REF_FTYPE_CRE values(2900, 'Armário Metálico');
insert into REF_FTYPE_CRE values(2900, 'Armário Óptico');
insert into REF_FTYPE_CRE values(11900, 'DISTRIBUIDOR GERAL OPT 19 36FBRS');
insert into REF_FTYPE_CRE values(11900, 'DISTRIBUIDOR OPTICO GERAL 19 12 FIBRAS');
insert into REF_FTYPE_CRE values(2400, 'TDUTO CORRUGADO PEAD DIAM 124 MM');
insert into REF_FTYPE_CRE values(2400, 'DUTO LISO PVC DIAM 100 X 6000 MM C/PB');
insert into REF_FTYPE_CRE values(2400, 'DUTO RD CORRUG P/FORA LISO P/DENT PEAD');
insert into REF_FTYPE_CRE values(2400, 'DUTO LISO ACO GALVAN DIAM 114 X 6000 MM');
insert into REF_FTYPE_CRE values(2400, 'NA');
insert into REF_FTYPE_CRE values(10800, 'CEM AÉREA N/SELADA 200PRS');
insert into REF_FTYPE_CRE values(10800, 'CEM AÉREA N/SELADA 400PRS');
insert into REF_FTYPE_CRE values(10800, 'CONJUNTO E. AÉREA ATÉ 100 PRS');
insert into REF_FTYPE_CRE values(10900, 'BASTIDOR ACO 10 PARES 1 BLOCO');
insert into REF_FTYPE_CRE values(10900, 'BASTIDOR ACO 20 PARES 2 BLOCOS');
insert into REF_FTYPE_CRE values(10900, 'BASTIDOR ACO 30 PARES 3 BLOCOS');
insert into REF_FTYPE_CRE values(10900, 'BASTIDOR ACO 50 PARES 5 BLOCOs');
insert into REF_FTYPE_CRE values(10900, 'Bastidor De Aco 100 Pares (10 Blocos)');
insert into REF_FTYPE_CRE values(10900, 'TERMINAL ACESSO REDE 10 PR TAR-10-3E.RAP');
insert into REF_FTYPE_CRE values(10900, 'TERMINAL ACESSO REDE 20 PR TAR-20-3E.RAP');
insert into REF_FTYPE_CRE values(10900, 'TERMINAL ACESSO REDE 10 PR TAR-10-3E.RAP');
insert into REF_FTYPE_CRE values(10900, 'TERMINAL ACESSO REDE 20 PR TAR-20-3E.RAP');
insert into REF_FTYPE_CRE values(19600, 'DISTRIBUIDOR GERAL OPT 19 24FBRS');
insert into REF_FTYPE_CRE values(19600, 'DISTRIBUIDOR GERAL OPT 19 36FBRS');
insert into REF_FTYPE_CRE values(19600, 'DISTRIBUIDOR OPTICO GERAL 19 12 FIBRAS');
insert into REF_FTYPE_CRE values(19600, 'SUB-BASTIDOR STOH 72 FIBRAS');
insert into REF_FTYPE_CRE values(11800, 'CEO AÉREA 18-36 FBRS FIX. POSTE');
insert into REF_FTYPE_CRE values(11800, 'CEO AÉREA 72 FBRS FIX. POSTE');
insert into REF_FTYPE_CRE values(11800, 'CEO AÉREA ATÉ 12 FBRS FIX. POSTE');
insert into REF_FTYPE_CRE values(11800, 'CEO SUBT 144 FBRS');
insert into REF_FTYPE_CRE values(11800, 'CEO SUBT 18-36 FBRS');
insert into REF_FTYPE_CRE values(11800, 'CEO SUBT 48-72 FBRS');
insert into REF_FTYPE_CRE values(11800, 'CEO SUBT ATÉ 12FBRS');
insert into REF_FTYPE_CRE values(19300, 'TRANSDUTOR PRESSAO CABO ENDERECADO INT');
commit;
--falta
--scripts vba
--script criação componente texto
--testar na nossa maquina
