
/*

ALTER TABLE B$GC_FTERM ADD FEATURE_TYPE VARCHAR2(200);


-- Este bloco abaixo recria views, triggers e outros objetos atrelado à tabela
UPDATE G3E_GENERALPARAMETER SET G3E_VALUE='1' WHERE G3E_NAME='IgnoreSubsettingForLTT';
COMMIT;

EXEC G3E_GENERALPARAMETER_PKG.CREATEOPTIMIZEDTABLE;
COMMIT;

BEGIN
  CREATE_VIEWS.CREATE_LTT_VIEW('B$GC_FTERM');
  CONSTRAINT_TRANSFER.GETPRIMARYCONSTRAINT('B$GC_FTERM');
  CONSTRAINT_TRANSFER.DROPUNIQUECONSTRAINT('B$GC_FTERM');
  CONSTRAINT_TRANSFER.DROPUNIQUEINDEX('B$GC_FTERM');
  CREATE_TRIGGERS.CREATE_LTT_TRIGGER('B$GC_FTERM');
END;
/

-- Este bloco abaixo recria views, triggers e outros objetos atrelado à tabela
UPDATE G3E_GENERALPARAMETER SET G3E_VALUE='0' WHERE G3E_NAME='IgnoreSubsettingForLTT';
COMMIT;

EXEC G3E_GENERALPARAMETER_PKG.CREATEOPTIMIZEDTABLE;
COMMIT;

create table REF_FTERM_FTYPE
(
TIPO VARCHAR2(200)
);


insert into g3e_picklist values(11906, 'REF_FTERM_FTYPE.TIPO','REF_FTERM_FTYPE', 'TIPO', 'TIPO', 'G3ERestricted', null, null, sysdate, null, 'TIPO', 1,null); 
commit;


-- Insere as novas colunas na tabela de metadados G3E_ATTRIBUTE
INSERT INTO G3E_ATTRIBUTE (G3E_ANO,G3E_CNO,G3E_FIELD,G3E_USERNAME,G3E_REQUIRED,G3E_COPY,G3E_EXCLUDEFROMEDIT,G3E_DATATYPE,G3E_EXCLUDEFROMREPLACE,G3E_EDITDATE,G3E_BREAKCOPY,G3E_COPYATTRIBUTE,G3E_WRAPTEXT,G3E_UNIQUE,G3E_FUNCTIONALVALIDATION,G3E_ROLE, g3e_pno) 
VALUES (1190119,11901,'FEATURE_TYPE','Tipo do DG (CRE)',0,0,0,10,0,SYSDATE,1,1,0,0,0,'EVERYONE',11906);
COMMIT;

--Popular ref

insert into REF_FTERM_FTYPE values('DISTRIBUIDOR GERAL OPT 19 36FBRS');
insert into REF_FTERM_FTYPE values('DISTRIBUIDOR OPTICO GERAL 19 12 FIBRAS');
commit;

-- Inserir na tabattribute
prompt Importing table g3e_tabattribute...

insert into g3e_tabattribute (G3E_TANO, G3E_ANO, G3E_ORDINAL, G3E_PNO, G3E_READONLY, G3E_DEFAULT, G3E_REFRESH, G3E_DTNO, G3E_FIELDVALUEFILTER, G3E_TRAVERSALANO, G3E_EDITDATE, G3E_TRIGGERPOPULATE, G3E_USEFILTERTOTRANSLATEKEY, G3E_FKQRINO, G3E_FKQARGGROUPNO)
values (1190126, 1190119, 26, 11901, 0, null, 0, 1190101, null, null, sysdate, 0, 0, null, null);

insert into g3e_tabattribute (G3E_TANO, G3E_ANO, G3E_ORDINAL, G3E_PNO, G3E_READONLY, G3E_DEFAULT, G3E_REFRESH, G3E_DTNO, G3E_FIELDVALUEFILTER, G3E_TRAVERSALANO, G3E_EDITDATE, G3E_TRIGGERPOPULATE, G3E_USEFILTERTOTRANSLATEKEY, G3E_FKQRINO, G3E_FKQARGGROUPNO)
values (1190226, 1190119, 26, 11901, 0, null, 0, 1190102, null, null, sysdate, 0, 0, null, null);


insert into g3e_tabattribute (G3E_TANO, G3E_ANO, G3E_ORDINAL, G3E_PNO, G3E_READONLY, G3E_DEFAULT, G3E_REFRESH, G3E_DTNO, G3E_FIELDVALUEFILTER, G3E_TRAVERSALANO, G3E_EDITDATE, G3E_TRIGGERPOPULATE, G3E_USEFILTERTOTRANSLATEKEY, G3E_FKQRINO, G3E_FKQARGGROUPNO)
values (1190326, 1190119, 26, 11901, 1, null, 0, 1190103, null, null, sysdate, 0, 0, null, null);

commit;


EXEC gc_compileinvalidobjects;
*/